inverseOperationIds:
  # List operations used by Flagsmith's LaucnhDarkly importer here.
  - getProject
  - getEnvironmentsByProject
  - getFeatureFlags
  - getSegments
unusedComponents:
  - schemas
  - parameters
  - examples
  - headers
  - requestBodies
  - responses
