name: Platform Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint-everything:
    name: Lint check the monorepo
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install Dependencies
        run: |
          cd api
          make install-packages-dev

      - name: Generate pre-commit cache key
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run Linters
        run: |
          pre-commit run --all-files black
          pre-commit run --all-files flake8
          pre-commit run --all-files prettier
